nationalarchives/tdr-consignment-api-data

lambda/src/main/resources/db/migration/V6__transfer_agreement_primary_key.sql
TransferAgreementId column added as auto-increment and as new primary key
ConsignmentId changed to foreign constraint key
MySql requires primary keys to be auto incremented to enable returning value when inserting: https://scala-slick.org/doc/3.1.1/queries.html#inserting
=> Add migration to add new id column

README.md, build.sbt
Some developers are already running MySQL natively on their machines for another project. This will allow them to run a Dockerized MySQL on a different port.
Also add links and code generation instructions to README.
=> Parameterize database port

lambda/src/main/resources/db/migration/V8__client_file_metadata_primary_key.sql
MySql requires primary key to be auto increment field
As FileId column is a foreign key constraint coming from the File table it is
not suitable as the primary key as it cannot be auto increment as the
value comes from another table
Add new column to be the primary key and make this auto increment
Reinstate FileId as a foreign key constraint
Following similar approach for the TransferAgreement table
=> Migration to add auto increment column

README.md, lambda/src/main/resources/db/migration/V9__make_antivirus_fields_mandatory.sql
The antivirus scan should always generate these fields, so there is no need for them to be nullable. It only adds more Option handling to the API and its client.
Leave the `value` field nullable because it will be removed soon, since it is not used.
Once this is merged, I'll make the fields non-nullable in the API.
=> Make antivirus metadata fields mandatory

lambda/src/main/resources/db/migration/V9__make_antivirus_fields_mandatory.sql
The migration failed in integration because some of the rows had null antivirus data. This is probably because of test data, so it should be safe to insert placeholder values into those fields.
=> Fix migration to make antivirus fields non-null

Jenkinsfile-run-migrations
The Jenkinsfile which runs the migrations just triggers the migrations lambda - it doesn't wait for the lambda to finish. So we need to add a delay before running the end-to-end tests, to make it more likely that the migration has finished before the e2e tests start.
=> Add a delay before running the end-to-end tests

lambda/src/main/resources/db/migration/V10__delete_antivirus_value_column.sql
This column was not used. The result of the antivirus scan is stored in the "Result" column.
The API does not save any data to this column, so it's safe to delete.
We'll have to be careful when releasing this, because the API uses the generated DB library which does reference the `Value` column, even though it just tries to save nulls to it. Release steps:
=> Add migration to delete "Value" column from antivirus metadata

Jenkinsfile-publish-library
The S3 publishing script needs to call the `s3publish-intg` ECS task to publish the library.
This step broke recently when we split up the Jenkinsfiles for deploying the migrations and publishing the library, because the `STAGE` parameter was omitted from Jenkinsfile-publish-library.
Hard-code the "intg" suffix for now. In future it should be removed altogether, because the library is published once to the management account, rather than separately to each TDR environment: https://national-archives.atlassian.net/browse/TDR-465
Also fix the indentation, so this PR is probably easiest to review commit-by-commit.
=> Fix name of ECS task used to publish library to S3

lambda/src/main/resources/db/migration/V11__add_parent_folder_to_consignment.sql
This will allow us to later show the user that their specified folder has successfully been uploaded and the user can ensure that it is the folder they intended to upload
=> Add ParentFolder column to Consignment table

Jenkinsfile-publish-library
The task definition s3Publish has been updated in the management account
so we don't need to use the old manually created task definition now.
=> Remove the stage from the task definition.

lambda/src/main/resources/db/migration/V15__add-client-side-properties-to-file-property.sql
I haven't moved the existing entries in yet. This will need doing when
the ClientFileMetadata table is deleted so there's no point doing it
now.
=> Add the FileProperty entries for client side metadata

version.sbt
Manual bump required as versions got out of snyc following testing fix on separate branch using different Jenkins job
Once version is bumped will need to re-run the Migrations Publish Jenkins job to update the pg_dump.sql with the latest changes
=> Manually bump version

version.sbt
Version 0.0.37 cannot be published because of some issues with the Jenkins build image.
=> Manually bump version to 0.0.38

lambda/src/main/resources/db/migration/V19__remove_duplicate_consignment_properties.sql
V17 and V18 migrations both add properties named: 'FinalOpenRecordsConfirmed' and 'LegalOwnershipTransferConfirmed'
Remove the properties and re-add them with new uuids as not clear which version of the properties should be used
=> Remove duplicate consignment properties

Jenkinsfile-publish-library
If you don't include a version, it just chooses the latest one.
=> Remove the hard coded version.

lambda/src/main/resources/db/migration/V21__change_consignment_metata_foreign_key.sql
Unnecessary complexity was being caused by having the 'PropertyId' included in the 'ConsignmentMetadata' table as the property name was needed for the API
Decision to include the property name in the 'ConsignmentMetadata' table to remove complexity
'PropertyId' no longer required in the 'ConsignmentProperty' table as the property name is unique and can be used as the primary key in that table
=> Make 'Name' primary key for 'ConsignmentProperty' table

version.sbt
It looks like the versions are out of sync. version.sbt is on 42-SNAPSHOT but version 42 already exists so I'm manually bumping this to get us onto the next version.
=> Manual version bump

lambda/src/main/resources/db/migration/V29__rename_consignment_seq.sql
As we are using a H2 DB for testing and Postgres for production, some tests were failing due to the different DB interpretations of the same SQL lines. The simplest solution seems to be to change the consignment sequence object to lower_snake_case, to allow production and test DB's to work effectively.
=> Change consignment sequence name to allow testing and production to work

lambda/src/main/resources/db/migration/V31__add_consignment_status_table.sql
This will allow us to track the status of consignments in order to show the user an error if they try to upload a folder when an upload has already taken place.
=> Add `ConsignmentStatus` table with associated columns

lambda/src/main/resources/db/migration/V33__alter_consignment_status_table.sql
This will allow us to alter the use of the ConsignmentStatus table to have only _one_ row per consignment which gets altered when a consignment status is updated. This includes the constraint to ensure ConsignmentId and StatusType are always a unique combination.
=> Add ModifiedDateTime column and unique constraint to consignmentStatus table

lambda/src/main/resources/db/migration/V34__remove_default_consignment_sequence.sql
The consignment sequence is being incremented twice. It's being called with `select nextval('consignment_sequence_id')` and then it's being called again with the insert to the Consignment table.
If we want to keep the consignment reference mandatory, which we do, then the only option seems to be to remove the default. At no point are we inserting an empty value in here so we don't need the default.
=> TDR-1073 Remove default consignment sequence.

lambda/src/main/resources/db/migration/V36__create_real_body_and_series.sql
I've added the Body and Series using a Do script so that variables could be used to return the Body UUID to insert into the Series table. I also saw that some columns in both the body and series table were nullable which shouldn't really be. I have therefore corrected  this as part of the script. I also saw that the Body Code column still existed which should have been removed as part of an earlier update on the schema. I have removed the column as part of this as well.
=> Added script to add new bodies and series plus some table alterations

Jenkinsfile-publish-library
The task name was changed a while ago to sbtwithpostgres.
The image hasn't been updated since then so we've not had any problems
but it has now so we need to change it to the image that's being managed
in terraform.
=> Replace task definition name

Jenkinsfile-deploy-migrations, Jenkinsfile-publish-library, build.sbt, notes/0.0.57.markdown, notes/0.0.58.markdown, project/plugins.sbt, version.sbt
The performance checks need a jar file for the lambda in Github releases. This modifies the existing S3 release process to release to GitHub as well. 
This copies the process from the export where changelog notes are generated from the commit log.
I've also made the assembly jar name static and updated the deploy job to work with this.
=> Create a GitHub release for the lambda jar

lambda/src/main/resources/db/migration/V42__backfill_consignment_type.sql
Backfill existing rows with 'ConsignmentType' standard as no judgment consignments will have been created prior
Ensures no gaps in the existing data
=> 'ConsignmentType' required

Jenkinsfile-publish-library
If the database migration doesn't change the pg_dump.sql file, if it's
only a data update for example, then git commit returns exit code 1
which fails the Jenkins build.
If there is nothing to commit that's fine so we can just ignore the
error message by adding || true.
=> Ignore unchanged pg_dump.sql file

build.sbt
The lambda deploy job is tagging the release so this doesn't have to.
=> Don't tag the release.

.github/workflows/build.yml, .github/workflows/publish.yml
When we publish the db utils, it creates a PR for the version bump. This
is currently triggering the lambda deploy.
This should add a version bump label on publish. The build job will only
run for PRs that don't have this label.
=> Don't run the lambda deploy on a version bump PR.

src/main/resources/pg_dump.sql, version.sbt
This failed because the Version bump label didn't exist and now it won't
overwrite the existing version so I've manually created this to get the
build running again.
The existing 0.1.14 version will be a available for use.
=> Version bump PR.

lambda/src/main/resources/db/migration/V66__DisallowedPuids_add_active_column.sql
Having 'Active' column wil let clients filter on whether to use the disallowed puid or not
At the moment TDR accepts certain puids but in the future will not. Can add these puids values to the table whilst still accepting files with that puid value
=> 'Active' column added for disallowed puids

lambda/src/main/resources/db/migration/V70__add_non_judgment_format_to_disallowed.sql
If a judgment user uploads a non docx file, they get a status of
`NonJudgmentFormat` which isn't allowed so needs to be added to the
disallowed table.
=> Add non judgment to disallowed list.

lambda/src/main/resources/db/migration/V74__add_ordinal_to_FilePropertyValues_and_expand_Foi_Exemptions.sql
Add ordinal column to FilePropertyValues and expand to full list of FOI exemption codes including order of most common. Also removes open value.
=> Add ordinal column to FilePropertyValues and expand FOI exemption codes

build.sbt
Since the upgrade of flyway, it now needs a list of database plugins
which it gets from the META-INF services directory.
sbt assembly was discarding this, this line will keep it.
=> Include META-INF services

lambda/src/main/resources/db/migration/V104__update_display_properties_alternate_title.sql
This ticket asks for hint text to be added to the AlternateTitle field.
In other places, we're using the description for hint text and it doesn't look like we're using the description for this field for anything at the moment so I think this is ok.
I'll update the frontend to use this on the page. https://github.com/nationalarchives/tdr-transfer-frontend/pull/2674
=> TDR-2852 Update TitleAlternate description.

lambda/src/main/resources/db/migration/v105__display_properties_description.sql
This is to allow us to add text to a GDS details component.
Front end changes are here
https://github.com/nationalarchives/tdr-transfer-frontend/pull/2693
I've also updated the `description` Description to match the prototype.
=> TDR-2905 Add details summary and text.

.github/scripts/create-user.sql, .github/workflows/test.yml, build.sbt
Because the real migration uses the migrations_user and the test is running with admin permissions, we can have problems where the tests pass but the run in the lambda fails because of permissions issues.
This creates a user with the same permissions as the migrations user we use for production.
=> TDR-2586 use correct permissions

.github/workflows/test.yml
The tests are run on a clean database which means if there are changes which break existing migrations, they won't be caught. This runs them on master first and then against the branch to try and catch these errors.
=> Run tests on master first

.github/workflows/publish.yml
The user in the build.sbt file is migrations_user but it hasn't been
created inside the publish job. This is the same scripts the tests use
to this should work.
=> Create migrations_user in publish job

lambda/src/main/resources/db/migration/V107__Insert_displayproperties_data.sql
Decoupling whether a field is required in the UI from whether the data schema requires the field
There are instances where a field is not required in the data schema, but need to force the user to actively enter a value in the UI, for example 'ClosureStartDate' field
=> Add 'Required' property to support UI

lambda/src/main/resources/db/migration/V114__backfill-include-folder-flag.sql
This is only for the judgment users.
=> Backfill includeTopLevel folder flag.

lambda/src/main/resources/db/migration/V118__drop_shortname_consignmentproperty.sql
Upon dropping the column, generating the slick classes and running through the whole upload process everything was still working.
=> TDR-635 Drop shortname from the ConsignmentProperty table

lambda/src/main/resources/db/migration/V127__fix_ffidmetadatamatches_mismatch_and_format_name.sql
Original migration (V126) did not double quote the column names so formatting was defaulted to lower casing
Naming convention for column names should be camel case
=> Enforce 'camel case' naming on columns

.github/workflows/test.yml
The version bump pr's were stuck waiting for the checks because we only enabled checks for commits and not on pull requests. This adds this change.
=> Run tests on pull request

.github/workflows/publish.yml, version.sbt
By default ubuntu-latest Github action images ships with version 14 of postgresql
As DB has been upgraded to version 17 need this version of postgresql to run the 'pg_dump' command otherwise an incompatiblity error is thrown
Previous version requires purging first otherwise it still appears as the version used
=> Upgrade postgresql to version 17

lambda/src/main/resources/db/migration/V165__add_match_id_to_file_table.sql
Allow persistence of match id used during upload
To support the processing of transfers from sources other than the TDR web application the match id is required for the backend checks to work
Will allow the correct identification of objects within S3 buckets and remove the need for copying objects within the 'dirty' bucket
=> Sptdr match id column
