Jenkinsfile-deploy, Jenkinsfile-publish
AWS container upgraded to python3
Updating Jenkins script to reference python3
=> Upgrade Jenkins script to python3

Jenkinsfile-deploy, Jenkinsfile-publish
- Reword messages for clarity
- Switch Slack channel so that releases don't spam the main TDR channel
=> Slack messages

lambda/src/main/resources/db/migration/V7__alter_ffid_table.sql, version.sbt
There were a few changes from when this table was originally created so
I've dropped and recreated the table.
The only allowed null field is the extension which may be null if there
isn't one on the uploaded file.
I've asked David and he's happy with the structure.
=> Update the FFIDMetadata table

lambda/src/main/resources/db/migration/V8__add-matches-table, lambda/src/main/resources/db/migration/V8__add-matches-table.sql, version.sbt
* It's possible to have more than one match for a file.
* I've added another table to store the matches.
=> Add a table for FFID matches.

version.sbt
I accidentally closed the original PR #35.
=> Version Bump from build number 81

Jenkinsfile-publish-library
This runs pg_dump, outputs it to a file and commits and pushes it. The
PR for the version bump is then created later.
=> Add a stage to generate SQL dump

lambda/src/main/resources/db/migration/V52__create_judicial_office_body.sql
This is the transferring body for the judiciary that transfer any judgments
=> Add 'Judicial Office' transferring body

lambda/src/main/resources/db/migration/V53__folder_data_backfill.sql
SQL script to create and backfill folder data plus  update files with names types etc.
=> folder data backfill script

.github/workflows/test.yml
This is just a sense check to make sure flyway runs properly before
merging.
=> Add a test by running flywayMigrate

lambda/src/main/resources/db/migration/V65__FileStatus_correct_checksum_match_property.sql
Migrated 'StatusType' to incorrect name
=> Use correct name for status type

lambda/src/main/resources/db/migration/V67__add_disallowed_puids.sql
Requires PR: https://github.com/nationalarchives/tdr-consignment-api/pull/376
=> Add additional disallowed puids

lambda/src/main/resources/db/migration/V67__Add_Ordinal_column.sql
Created script to add the Ordinal column to the FileProperty table.
=> Tdr 2189 add ordinal column

lambda/src/main/resources/db/migration/V69__update-ordinal-column.sql
I've based this off the design in this ticket
https://national-archives.atlassian.net/browse/TDR-2057
=> Add the ordinal values for the custom metadata

lambda/src/main/resources/db/migration/V75__remove_default_closure_period.sql
Removes the default value row for closure period in FilePropertyValues
=> remove closure period default value

lambda/src/main/resources/db/migration/V71__add_ui_element_descriptions_to_FileProperty_table.sql
=> Added new migration to set Description values for several UI elements in the FileProperty table

lambda/src/main/resources/db/migration/V78_rename_TitlePublic_to_TitleClosed_in_FilePropertyDependenciesTable.sql
New migration file as approved in Jira.
=> Tdr 2385 rename title public in file property dependencies

lambda/src/main/resources/db/migration/V79__Foreign_key_creation_for_file_property_tables.sql
I seem to have not moved this forward to the PR. Doing that now.
=> Added migration file

lambda/src/main/resources/db/migration/V81__Update_of_fileproperty_export_data.sql
@TomJKing @MancunianSam Please could you have a look at this script and check it meets what we talked about. I can go through it in a db to show you if required. Also might it be better to space the ordinal values every 5 (5,10,15...) to allow jiggle room later on.
=> Script for Export data update

lambda/src/main/resources/db/migration/V82__Indexes_for_reporting.sql
=> Tdr 2355 reporting indexes

lambda/src/main/resources/db/migration/V83__Rename_of_DescriptionPublic.sql
@thanhz @TomJKing Script to rename public description. These are much trickier now we have constraints and there are several tables to update. Commits inline to add with less memory and speed it up. Previous new indexes also helped.
=> New script to rename descriptionpublic

lambda/src/main/resources/db/migration/V84__New_Body_and_series_for_testing.sql
Script ready for review if you want to push it through this sprint @TomJKing
=> New Body and series for testing purposes

lambda/src/main/resources/db/migration/V83__Rename_of_DescriptionPublic.sql
Hopefully dropping constraints works
=> Tdr 2547 description public amendments

lambda/src/main/resources/db/migration/V91__update_language_property.sql
'English and Welsh' value not needed as languages will be added as separate values
'Language' property can have more than one value so make property multiple value
=> Update 'Language' file property

lambda/src/main/resources/db/migration/V103__update_displayproperties.sql
For correct display order on the summary page
=> TDR-2798 Insert 'Ordinal' for 'DescriptionAlternate' & 'TitleAlternate'

build.sbt
I didn't notice this, it was found by someone else.
=> Replace missed set-output command.

lambda/src/main/resources/db/migration/V111__update_titleClosed_and_descriptionClosed_values.sql
Set the boolean values to lowercase to be consistent with user supplied values
=> TDR-2987 - Update DescriptionClosed and TitleClosed Values

lambda/src/main/resources/db/migration/V119__getConsignment_further_indexes.sql
@TomJKing could you review? Cheers.
=> add new indexes for ConsignmentAPI

lambda/src/main/resources/db/migration/V125__ons_additional_series.sql
Series added:
- RG 53
- RG 75
- RG 121
- LAB 17
=> Additional series for ONS body

.github/workflows/build.yml, lambda/src/main/scala/migration/Main.scala
Rds certficate bundle downloaded from here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions
=> TDR-3504 update rds certificate

lambda/src/main/resources/db/migration/V143__backfill_tdrbodycode_column_from_body_table.sql, lambda/src/main/resources/db/migration/V143_backfill_tdrbodycode_column_from_body_table.sql
=> TDR-3562 Backfill TDR Bodycode to Consignment table

lambda/src/main/resources/db/migration/V155__extend_disallowed_puids.sql
Updated disallowed puids to be active (true)
Added new disallowed puids
=> Extend disallowed puids

lambda/src/main/resources/db/migration/V160__add_ja1342_1416_1417_series.sql
=> added 3 new series for NICE

README.md, lambda/src/main/resources/db/migration/V161__create_information_commisioners_office_body.sql
Added Information Commissioners Office 
GitHub co-pilot changed format of Readme to allow it to open in Intellij
=> Add  Information Commissioners Office
